export const SCORING_RULES = {
  stale: {
    days1000: 45,
    days730: 38,
    days365: 30,
    days180: 20,
    days90: 10,
    oldOpenIssuesBonus: 10,
    notArchivedOldBonus: 10,
    archivedPenalty: -25,
    forkPenalty: -20,
    popularPenalty: -8,
  },
  oneDay: {
    activeDays1: 40,
    activeDays3: 25,
    activeDays7: 15,
    noDescriptionBonus: 15,
    zeroStarBonus: 10,
    temporaryNameBonus: 20,
    archivedPenalty: -15,
    forkPenalty: -20,
  },
  initialCommitPortrait: {
    maxActiveDays: 1,
    minDaysSincePush: 365,
    score: 100,
  },
  nameShameKeywords: [
    "test",
    "practice",
    "sample",
    "todo",
    "my-app",
    "new-app",
    "untitled",
    "copy",
    "backup",
    "old",
    "tmp",
    "demo",
    "hoge",
    "foo",
    "bar",
    "勉強",
    "練習",
  ] as readonly string[],
} as const;
